### ISSUE TITLE
一些问题和建议

### ISSUE THREAD

**Issue by wordpure** [abgox/abgo_bucket#1]
1.  特殊文件夹路径

Windows 的桌面、文档、图片、音乐、视频、下载这几个文件夹都支持用户自定义位置，应该通过 Shell 或注册表来获取，而不能直接用 `$env:UserProfile` 拼接。

![图片](https://github.com/abgox/abgo_bucket/assets/68013962/ce0398ee-e15e-4a9a-8dc1-e1f47ab0955b)

![图片](https://github.com/abgox/abgo_bucket/assets/68013962/ffb497e8-9427-440b-83f5-1fcfaa3177cd)

<details>

<summary>示例</summary>

```powershell
# 下载
Get-ItemProperty -Path 'Registry::HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders' -Name '{374DE290-123F-4565-9164-39C4925E467B}' | Select-Object -ExpandProperty '{374DE290-123F-4565-9164-39C4925E467B}'

# 桌面
[Environment]::GetFolderPath("Desktop")

# 文档
[Environment]::GetFolderPath([Environment+SpecialFolder]::MyDocuments)

# 图片
[Environment]::GetFolderPath([Environment+SpecialFolder]::MyPictures)

# 音乐
[Environment]::GetFolderPath([Environment+SpecialFolder]::MyMusic)

# 视频
[Environment]::GetFolderPath([Environment+SpecialFolder]::MyVideos)
```

</details>

2. 报错提示

桌面文件夹被我移到 D 盘去了，所以脚本没法在一个不存在的文件夹下面创建快捷方式，但它还是显示了绿色的成功文本。我特地去看了一下才发现没有创建成功。

![图片](https://github.com/abgox/abgo_bucket/assets/68013962/ece0b9e8-a984-4cf5-8748-cec364e59a11)

顺便问下，桌面快捷方式能不能作为一个可选项提供？因为有些用户（比如我）的桌面其实是不放东西的😂

3. 更新检测

Quicker 官方有提供 [版本更新 API](https://getquicker.net/KC/Help/Doc/public-api#crZxB)。

![图片](https://github.com/abgox/abgo_bucket/assets/68013962/4a9e9f6a-31ee-4203-8602-b00096cbb221)

Pixpin 也可以通过抓请求来获取 [版本检测 API](https://accounts.viewdepth.cn/deepviewapi/public/pixpin/info)。

![图片](https://github.com/abgox/abgo_bucket/assets/68013962/1f49ef56-98e1-4850-9d52-95345ca59098)

4. 持久化数据

pot 没有备份翻译历史，插件也是等卸载完才挪回 `persist` 的，但这样就没法直接打包到其他电脑使用了。感觉把所在文件夹整个备份起来会比较合理。

![图片](https://github.com/abgox/abgo_bucket/assets/68013962/cbd688d5-2ee1-4ce9-b3f7-2b4916011df0)

Pixpin 的持久化数据漏了截屏历史。

![图片](https://github.com/abgox/abgo_bucket/assets/68013962/10fc9c8a-8345-4b1e-be82-406249c5f18c)

**Comment by abgox** [comment]
1. 特殊文件夹路径
   - 这确实是我没有思考过的问题，我也没有尝试过去修改默认位置，大部分用户应该也不会去修改。
   - 不过我会在测试过后，替换掉原本 `$env:UserProfile`
   - 这会引发另一个问题，是否所有以 `$env:xxx` 去拼接的路径都不应该使用，比如 `$env:AppData` 这样的
   - 后面会处理这些问题

2. 桌面快捷方式的可选项
   - 考虑过在更新中让用户手动确认，但是这样的话，应用的安装就很难达到自动化执行，会卡在确认流程
   - 正在考虑一种好的方式，比如能否在安装时多添加一个参数，然后获取这个参数来判断
3. 更新检测
   - 既然有了官方提供的更新 API，我会替换掉原本使用的检测方式
4. 持久化数据
  - Pot
     - Pot 的插件目录在我的测试下，如果使用链接会导致软件的插件配置页直接卡死
     - 所以才使用移动目录这样的方式
     - 后面我考虑一下，使用 `abgo_bucket` 提供的 `schedule` 来实现同步
  - PixPin 
    - 截屏历史，后面会加上

**Comment by wordpure** [comment]
> * 这会引发另一个问题，是否所有以 `$env:xxx` 去拼接的路径都不应该使用，比如 `$env:AppData` 这样的

支持用户自定义的系统目录应该就桌面、文档、图片、音乐、视频、下载这几个，不过用 shell 或注册表代替字符串拼接可能更优雅一些。

> 对于 `.exe` 安装
> 
>     * 是直接使用 `exe` 静默安装的，安装程序会创建桌面图标

我也是后面才发现，pot 会自动在桌面创建图标。pot 仓库还有位用户提了 [issue](https://github.com/pot-app/pot-desktop/issues/723) 希望能把它去掉😂

> * 特殊文件夹: 已解决
> 
> * 桌面快捷方式
>   
>   * 使用 `scoop config abgo_bucket_no_shortcut true` 来禁用桌面快捷方式的生成
>   * [详情查看 README 中的关于快捷方式](https://github.com/abgox/abgo_bucket/blob/main/README-CN.md?rgh-link-date=2024-03-05T10%3A22%3A28Z#%E5%85%B3%E4%BA%8E%E5%BF%AB%E6%8D%B7%E6%96%B9%E5%BC%8F)
> 
> * 更新检测: 已解决
> 
> * 持久化数据: 已解决

感谢🌹

**Comment by abgox** [comment]
- 现在  `abgo_bucket_no_shortcut` 配置项适用于 `abgo_bucket` 下的所有的应用
  - 对于 `.exe` 安装程序，如果将此配置项设置为 `true`，会在安装过程中启动一个后台任务监控是否创建桌面快捷方式，当桌面快捷方式创建时，会立即被删除
