### ISSUE TITLE
【功能请求】增加一个「更新时是否自动删除旧版目录」的选项

### ISSUE THREAD

**Issue by wordpure** [abgox/abgo_bucket#3]
保留旧版目录有两个好处：

1. 在新版本存在 BUG，或有不称心的变动（删了喜欢的功能、加了不喜欢的功能）时可以及时回退。
2. 在新版本有破坏性更改，或是 persist 策略有疏漏时方便恢复应用数据。

另外，希望大佬能在 readme 里提一下 abgo 更新时默认会删除旧有应用目录，因为 Scoop 官方和大部分第三方 bucket 默认都是保留旧版目录的。

**Comment by abgox** [comment]
- 如果要保留旧版目录的话，就意味着在更新时不卸载软件，直接更新软件，但由于有许多软件使用的是 exe 直接安装，不知道会不会导致一些意外冲突，后面考虑一下吧。
- 当前，如果你想要回退版本的话，也还是有一个办法的。
  - 比如: `scoop install font-hack@3.2.0` ，scoop 会自动生成一个 3.2.0 版本的应用清单 json(放在 `workspace` 文件夹中)，然后尝试安装 3.2.0 版本
  - 你可以使用这样的方式尝试回退版本
  - 但是它只适用于应用每一个版本的安装包路径(url)是唯一的才行，如 `font-hack`
    - 3.2.1 版本: `https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/Hack.zip`
    - 3.2.0 版本: `https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.0/Hack.zip`

**Comment by abgox** [comment]
而且还有个别软件，软件本体都不在 scoop 目录下，只是使用 scoop 进行用户数据的 persist ，以及安装、卸载和更新

**Comment by wordpure** [comment]
> 如果要保留旧版目录的话，就意味着在更新时不卸载软件，直接更新软件，但由于有许多软件使用的是 exe 直接安装，不知道会不会导致一些意外冲突，后面考虑一下吧。

感觉有这种情况的软件是少数，改成在 manifest 里特殊处理一下会不会比较好？

或者为了保险起见，通过 exe 安装的软件采用这种先卸载再安装的方式，有提供便携版的软件则在 manifest 里特殊处理，保留旧版目录怎么样？

> 而且还有个别软件，软件本体都不在 scoop 目录下，只是使用 scoop 进行用户数据的 persist ，以及安装、卸载和更新

见识少了😂

**Comment by abgox** [comment]
- 现在调整了一下，和官方保持一致，默认也保留旧版本目录
- 添加了 `abgo_bucket_no_old_version` 配置，如果设置为  `true` 才会在更新时移除旧版本目录
- 不过这个调整只对便携版的软件有效，使用了官方卸载程序的应用还是会先执行官方卸载程序，然后在安装新版本
