### ISSUE TITLE
将中文 readme 的 Gitee 链接改为对应的 GitHub 链接

### ISSUE THREAD

**Issue by wordpure** [abgox/abgo_bucket#4]
![图片](https://github.com/abgox/abgo_bucket/assets/68013962/c9958414-9515-48f3-9dd9-a7be2188a0f9)

![图片](https://github.com/abgox/abgo_bucket/assets/68013962/ed70e442-66da-46ac-b50e-eb659949e034)

这两个地方给的都是 Gitee 的链接，但既然都能在 GitHub 上看中文 readme 了 ，它们也有对应的 GitHub 链接，那也没必要登录 Gitee 去看。

![图片](https://github.com/abgox/abgo_bucket/assets/68013962/31c1f73a-ab01-4e27-be58-d3a6faec6df3)

**Comment by abgox** [comment]
- 实际上, `README-CN.md` 更多的就是给国内用户在 gitee 上查看的
- 因为 gitee 会默认展示 `README-CN.md`, github 默认展示 `README.md`
- 而有的国内用户，上不了 github，这个 `README-CN.md` 中的链接，主要就是照顾这部分人
- 如果能访问 github 的话，不想使用 gitee，就在 `README.md` 中找到对应的链接查看即可

**Comment by wordpure** [comment]
> 因为 gitee 会默认展示 `README-CN.md`, github 默认展示 `README.md`

长知识了👍
