### ISSUE TITLE
Obsidian 和 Pixpin Beta 最新版的更新检测失效

### ISSUE THREAD

**Issue by wordpure** [abgox/abgo_bucket#5]
[Obsidian.json](https://github.com/ScoopInstaller/Extras/blob/master/bucket/obsidian.json) 失效的原因是 [1.6.5](https://github.com/obsidianmd/obsidian-releases/releases) 的 `Obsidian.$version.exe` 变成了 `Obsidian-$version.exe`。

![image](https://github.com/user-attachments/assets/97cfd519-5193-4dd2-9f0d-1a5136e7aee1)

[PixpinBeta.json](https://github.com/abgox/abgo_bucket/blob/main/bucket/PixPinBeta.json) 的正则好像没问题，不过也没检测到 [API](https://accounts.viewdepth.cn/deepviewapi/public/pixpin/info) 的更新。

![image](https://github.com/user-attachments/assets/31cd9987-67bb-463c-9ee9-b15b22bf9471)

**Comment by abgox** [comment]
- [Obsidian.json](https://github.com/ScoopInstaller/Extras/blob/master/bucket/obsidian.json) 现在看来是去掉了多架构版本了，只提供一个 exe 了
- [PixpinBeta](https://github.com/abgox/abgo_bucket/blob/main/bucket/PixPinBeta.json) 的正则是没有问题的，但是 checkver.ps1 却匹配不到值，很奇怪
- 暂时就用个取巧的办法，反向匹配第一个版本号

**Comment by wordpure** [comment]
PixPin 测试版昨天又更新了，软件弹出了更新提醒，不过 bucket 还是没有检测到。

抓了下 PixPin 的更新请求，发现 API 变成了 `https://api.viewdepth.cn/app_info?app_id=pixpin&update_type=1&sys=win`，检测的结果要比原本的 `https://accounts.viewdepth.cn/deepviewapi/public/pixpin/info` 更新。

感觉可以把 [PinPinBeta](https://github.com/abgox/abgo_bucket/blob/main/bucket/PixPinBeta.json) 的 checkver 换成新的这个。

![图片](https://github.com/user-attachments/assets/8f918aa6-78a7-463e-b46d-e9f8527a8ce9)

PS：PixPin 正式版（1.7.6）的更新检测 API 还没换，不过也说不准下次更新之后会不会变。
